### ISSUE TITLE
The test accuracy is too low. and the img is from brainwash,I use the model by the author provided

### ISSUE THREAD

**Issue by silencezx** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#17] opened 2019-01-04 09:39 UTC
![_20190104173903](https://user-images.githubusercontent.com/36003995/50681771-a34d8600-1047-11e9-83d9-71f02103b5e5.png)

**Comment by silencezx** [comment] 2019-01-04 09:41
![_20190104173903](https://user-images.githubusercontent.com/36003995/50681826-cc6e1680-1047-11e9-9502-6c907c2ed8dd.png)

**Comment by aditya-vora** [comment] 2019-01-04 10:20
@silencezx This is a duplicate of the previously raised issue. Please follow the given [link](https://github.com/aditya-vora/FCHD-Fully-Convolutional-Head-Detector/issues/15).

To my knowledge, this displacement error should not occur as I tested the model a few days back. However, since you are facing the issue which you can resolve it from the given link.

**Closed** 2019-01-04 10:20 UTC

**Comment by silencezx** [comment] 2019-01-04 10:35
> @silencezx This is a duplicate of the previously raised issue. Please follow the given [link](https://github.com/aditya-vora/FCHD-Fully-Convolutional-Head-Detector/issues/15).
> 
> To my knowledge, this displacement error should not occur as I tested the model a few days back. However, since you are facing the issue which you can resolve it from the given link.

Thanks brother,,, Solve the problem
